### ISSUE TITLE
macos neovim fish Iterm2: deoplete_go.py", line 250, in get_complete_result     result = loads(stdout_data.decode()) ValueError: Expected object or value

### ISSUE THREAD

**Issue by peterwillcn** [zchee/deoplete-go#154]
```
[deoplete] Traceback (most recent call last):
  File "/Users/macos/.vim/plugged/deoplete-go/rplugin/python3/deoplete/sources/deoplete_go.py", line 250, in get_complete_result
    result = loads(stdout_data.decode())
ValueError: Expected object or value
gocode decode error.  Use :messages / see above for error details.
[deoplete] Traceback (most recent call last):
  File "/Users/macos/.vim/plugged/deoplete-go/rplugin/python3/deoplete/sources/deoplete_go.py", line 250, in get_complete_result
    result = loads(stdout_data.decode())
ValueError: Expected object or value
.  Use :messages / see above for error details.
[deoplete] Traceback (most recent call last):
  File "/Users/macos/.vim/plugged/deoplete-go/rplugin/python3/deoplete/sources/deoplete_go.py", line 250, in get_complete_result
    result = loads(stdout_data.decode())
ValueError: Expected object or value
2019/05/29 00:24:22 rpc: can't find service Server.AutoComplete
.  Use :messages / see above for error details.
[deoplete] Traceback (most recent call last):
  File "/Users/macos/.vim/plugged/deoplete-go/rplugin/python3/deoplete/sources/deoplete_go.py", line 250, in get_complete_result
    result = loads(stdout_data.decode())
ValueError: Expected object or value
gocode decode error.  Use :messages / see above for error details.
[deoplete] Traceback (most recent call last):
  File "/Users/macos/.vim/plugged/deoplete-go/rplugin/python3/deoplete/sources/deoplete_go.py", line 250, in get_complete_result
    result = loads(stdout_data.decode())
ValueError: Expected object or value
.  Use :messages / see above for error details.
[deoplete] Traceback (most recent call last):
  File "/Users/macos/.vim/plugged/deoplete-go/rplugin/python3/deoplete/sources/deoplete_go.py", line 250, in get_complete_result
    result = loads(stdout_data.decode())
ValueError: Expected object or value
2019/05/29 00:24:25 rpc: can't find service Server.AutoComplete
.  Use :messages / see above for error details.
[deoplete] Traceback (most recent call last):
  File "/Users/macos/.vim/plugged/deoplete-go/rplugin/python3/deoplete/sources/deoplete_go.py", line 250, in get_complete_result
    result = loads(stdout_data.decode())
ValueError: Expected object or value
gocode decode error.  Use :messages / see above for error details.
[deoplete] Traceback (most recent call last):
  File "/Users/macos/.vim/plugged/deoplete-go/rplugin/python3/deoplete/sources/deoplete_go.py", line 250, in get_complete_result
    result = loads(stdout_data.decode())
ValueError: Expected object or value
.  Use :messages / see above for error details.
[deoplete] Traceback (most recent call last):
  File "/Users/macos/.vim/plugged/deoplete-go/rplugin/python3/deoplete/sources/deoplete_go.py", line 250, in get_complete_result
    result = loads(stdout_data.decode())
ValueError: Expected object or value
2019/05/29 00:24:43 rpc: can't find service Server.AutoComplete
.  Use :messages / see above for error details.
```

**Comment by Shougo** [comment]
I have tested https://github.com/stamblerre/gocode with go 1.12.5 and deoplete-go works.
I think you have used not supported gocode.

What gocode do you use?

**Comment by peterwillcn** [comment]
Upgrade gocode fixed! Thank you @Shougo

**Comment by Shougo** [comment]
OK.

**Comment by vuvgaG** [comment]
I'm having this issue with spacevim.  !!! the solutions above don't seem to cut it.

**Comment by vuvgaG** [comment]
https://github.com/SpaceVim/SpaceVim/issues/4147

**Comment by Shougo** [comment]
Please read the issue's comment.
