### ISSUE TITLE
error bug with deoplete-go

### ISSUE THREAD

**Issue by svanharmelen** [zchee/deoplete-go#56]
Using the latest or everything I sometimes get this:

```
[deoplete] Traceback (most recent call last):
[deoplete]   File "/Users/svanharmelen/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 47, in completion_begin
[deoplete]     complete_position, candidates = self.gather_candidates(context)
[deoplete]   File "/Users/svanharmelen/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 85, in gather_candidates
[deoplete]     results = self.gather_results(context)
[deoplete]   File "/Users/svanharmelen/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 158, in gather_results
[deoplete]     context['candidates'] = source.gather_candidates(context)
[deoplete]   File "/Users/svanharmelen/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/sources/buffer.py", line 24, in gather_candidates
[deoplete]     self.__make_cache(context, self.vim.current.buffer.number)
[deoplete]   File "/Users/svanharmelen/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/sources/buffer.py", line 57, in __make_cache
[deoplete]     p.findall(x) for x in self.vim.buffers[bufnr]
[deoplete]   File "/usr/local/lib/python3.5/site-packages/neovim/api/common.py", line 138, in __getitem__
[deoplete]     return self._fetch()[idx]
[deoplete] IndexError: list index out of range
[deoplete] An error has occurred. Please execute :messages command.
[deoplete] Traceback (most recent call last):
[deoplete]   File "/Users/svanharmelen/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 47, in completion_begin
[deoplete]     complete_position, candidates = self.gather_candidates(context)
[deoplete]   File "/Users/svanharmelen/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 85, in gather_candidates
[deoplete]     results = self.gather_results(context)
[deoplete]   File "/Users/svanharmelen/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 158, in gather_results
[deoplete]     context['candidates'] = source.gather_candidates(context)
[deoplete]   File "/Users/svanharmelen/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/sources/buffer.py", line 24, in gather_candidates
[deoplete]     self.__make_cache(context, self.vim.current.buffer.number)
[deoplete]   File "/Users/svanharmelen/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/sources/buffer.py", line 57, in __make_cache
[deoplete]     p.findall(x) for x in self.vim.buffers[bufnr]
[deoplete]   File "/usr/local/lib/python3.5/site-packages/neovim/api/common.py", line 138, in __getitem__
[deoplete]     return self._fetch()[idx]
[deoplete] IndexError: list index out of range
[deoplete] An error has occurred. Please execute :messages command.
[deoplete] Traceback (most recent call last):
[deoplete]   File "/Users/svanharmelen/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 47, in completion_begin
[deoplete]     complete_position, candidates = self.gather_candidates(context)
[deoplete]   File "/Users/svanharmelen/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 85, in gather_candidates
[deoplete]     results = self.gather_results(context)
[deoplete]   File "/Users/svanharmelen/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 158, in gather_results
[deoplete]     context['candidates'] = source.gather_candidates(context)
[deoplete]   File "/Users/svanharmelen/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/sources/buffer.py", line 24, in gather_candidates
[deoplete]     self.__make_cache(context, self.vim.current.buffer.number)
[deoplete]   File "/Users/svanharmelen/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/sources/buffer.py", line 57, in __make_cache
[deoplete]     p.findall(x) for x in self.vim.buffers[bufnr]
[deoplete]   File "/usr/local/lib/python3.5/site-packages/neovim/api/common.py", line 138, in __getitem__
[deoplete]     return self._fetch()[idx]
[deoplete] IndexError: list index out of range
[deoplete] An error has occurred. Please execute :messages command.
```

Any ideas?

**Comment by svanharmelen** [comment]
Ah, never mind... This is related to `deoplete.nvim` and not to `deoplete-go`. Will report it there...

**Comment by Shougo** [comment]
It is fixed in the latest deoplete.
