### ISSUE TITLE
TypeError: bytes() argument 2 must be str, not Nvim

### ISSUE THREAD

**Issue by dlogvinenko** [zchee/deoplete-go#58]
Neovim: 0.1.4 with latest deoplete-go and deoplete:

```
[deoplete] Traceback (most recent call last):
[deoplete]   File "/Users/dlogvinenko/.vim/bundle/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 48, in completion_begin
[deoplete]     complete_position, candidates = self.gather_candidates(context)
[deoplete]   File "/Users/dlogvinenko/.vim/bundle/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 82, in gather_candidates
[deoplete]     results = self.gather_results(context)
[deoplete]   File "/Users/dlogvinenko/.vim/bundle/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 133, in gather_results
[deoplete]     context['candidates'] = source.gather_candidates(context)
[deoplete]   File "/Users/dlogvinenko/.vim/bundle/deoplete-go/rplugin/python3/deoplete/sources/deoplete_go.py", line 103, in gather_candidates
[deoplete]     result = self.get_complete_result(buffer, context)
[deoplete]   File "/Users/dlogvinenko/.vim/bundle/deoplete-go/rplugin/python3/deoplete/sources/deoplete_go.py", line 190, in get_complete_result
[deoplete]     column) - 1
[deoplete]   File "/Users/dlogvinenko/.vim/bundle/deoplete.nvim/rplugin/python3/deoplete/util.py", line 72, in charpos2bytepos
[deoplete]     return len(bytes(input[: pos], encoding))
[deoplete] TypeError: bytes() argument 2 must be str, not Nvim
[deoplete] An error has occurred. Please execute :messages command.
```

**Comment by zchee** [comment]
@vort3x Thanks! and surprised \o/
It's known issue because deoplete.nvim core code has been changed `charpos2bytepos` API.
https://github.com/Shougo/deoplete.nvim/commit/2698f08c78c4862a972dfa10bed4fcd0a0fa9fa2
but it's commit is half an hour ago lol

I will fix and other local commit are push.
but, If you want to fix it immediately, please fix

``` python
charpos2bytepos(self.vim, context['input'][: column],
# to
charpos2bytepos('utf-8', context['input'][: column],
```

https://github.com/zchee/deoplete-go/blob/master/rplugin/python3/deoplete/sources/deoplete_go.py#L189

because Go is written only in utf-8.

**Comment by zchee** [comment]
@vort3x Now fixed :)

**Comment by dlogvinenko** [comment]
Thanks! Checked, works.

**Comment by zchee** [comment]
@vort3x 🎉
