### ISSUE TITLE
AttributeError: 'str' object has no attribute 'options'

### ISSUE THREAD

**Issue by ghost** [zchee/deoplete-go#60]
Hello,

I am using deoplete-go on ArchLinux and get the following error:

```
[deoplete] Traceback (most recent call last):                                                                                                      
[deoplete]   File "/home/nate/.cache/dein/.dein/rplugin/python3/deoplete/deoplete.py", line 47, in completion_begin                                
[deoplete]     complete_position, candidates = self.gather_candidates(context)                                                                     
[deoplete]   File "/home/nate/.cache/dein/.dein/rplugin/python3/deoplete/deoplete.py", line 85, in gather_candidates                               
[deoplete]     results = self.gather_results(context)                                                                                              
[deoplete]   File "/home/nate/.cache/dein/.dein/rplugin/python3/deoplete/deoplete.py", line 150, in gather_results                                 
[deoplete]     context['candidates'] = source.gather_candidates(context)                                                                           
[deoplete]   File "/home/nate/.cache/dein/repos/github.com/zchee/deoplete-go/rplugin/python3/deoplete/sources/deoplete_go.py", line 104, in gather_
candidates                                                                                                                                         
[deoplete]     result = self.get_complete_result(buffer, context)                                                                                  
[deoplete]   File "/home/nate/.cache/dein/repos/github.com/zchee/deoplete-go/rplugin/python3/deoplete/sources/deoplete_go.py", line 182, in get_com
plete_result                                                                                                                                       
[deoplete]     column) - 1                                                                                                                         
[deoplete]   File "/home/nate/.cache/dein/.dein/rplugin/python3/deoplete/util.py", line 68, in charpos2bytepos                                     
[deoplete]     return len(bytes(input[: pos], vim.options['encoding']))                                                                            
[deoplete] AttributeError: 'str' object has no attribute 'options'                                                                                 
[deoplete] An error has occurred. Please execute :messages command.
```

Deoplete itself works and and when I type `gocode -in main.go autocomplete 86` gocode returns:

```
Found 3 candidates:
  func main()
  package fmt 
  package mymath 
```

That means gocode works also.

It seems like the problem is with deoplete-go itself.

Thanks for any help!

**Comment by Shougo** [comment]
@dalliard It is not deoplete-go bug.
Your deoplete seems old.  Please update deoplete.

**Comment by ghost** [comment]
@Shougo Thanks for reaching out. I am using your Dein.vim. Doesn't it update the plugins by itself? If not, how can I update them?

**Comment by Shougo** [comment]
> @Shougo Thanks for reaching out. I am using your Dein.vim. Doesn't it update the plugins by itself? If not, how can I update them?

`call dein#update()`

**Comment by ghost** [comment]
> `call dein#update()`

Oh wow. My bad. Thanks!! Works fine now.
