### ISSUE TITLE
Whenever I enter insert mode I get huge errors

### ISSUE THREAD

**Issue by nikivdev** [zchee/deoplete-go#66]
I have downloaded the deoplete-go library as per the instructions and I believe I got everything right. Here is my [vimrc](https://github.com/nikitavoloboev/dotfiles/blob/master/vim/nvim/nvimrc#L182). 

The issue is that when I try and edit any file now, I get this screen : 

![2016-08-03 at 00 24](https://cloud.githubusercontent.com/assets/6391776/17347576/02c4d7b4-5911-11e6-9fe3-955357c099e8.png)

Thank you for any help.

**Comment by nhooyr** [comment]
Can you copy and paste the entire thing? It's hard to debug with just a screen shot.

**Comment by Shougo** [comment]
Yes.  The full error messages are important.
Please use `:redir` for it.

**Comment by nikivdev** [comment]
Here is the error in text 

```
error caught in async handler 'deoplete_on_event [{'camelcase': 0, 'bufnr': 1, 'rpc': 'deoplete_on_event', 'delay': 0, 'custom': {
'_': {}}, 'next_input': '', 'sources': [], 'ignorecase': 1, 'smartcase': 1, 'max_menu_width': 85, 'cwd': '/Users/nikivi/code/go/le
arning/learning_go', 'position': [0, 7, 2, 0], 'bufname': 'break.go', 'keyword_patterns': '[a-zA-Z_][a-zA-Z@0-9_À-ÿ]*', 'max_abbr_
width': 85, 'omni__omnifunc': 'go#complete#Complete', 'input': '\t', 'filetypes': ['go'], 'start_complete': '\udc80\udcfdR(deoplet
e_start_complete)', 'event': '', 'bufvars': {}, 'dict__dictionary': '', 'runtimepath': '/Users/nikivi/.config/nvim,/Users/nikivi/.
config/nvim/plugged/vim-sensible/,/Users/nikivi/.config/nvim/plugged/vimproc.vim/,/Users/nikivi/.config/nvim/plugged/dash.vim/,/Us
ers/nikivi/.config/nvim/plugged/gruvbox/,/Users/nikivi/.config/nvim/plugged/vim-fugitive/,/Users/nikivi/.config/nvim/plugged/vim-a
irline/,/Users/nikivi/.config/nvim/plugged/vim-airline-themes/,/Users/nikivi/.config/nvim/plugged/vim-easymotion/,/Users/nikivi/.c
onfig/nvim/plugged/nerdcommenter/,/Users/nikivi/.config/nvim/plugged/nerdtree/,/Users/nikivi/.config/nvim/plugged/ctrlp.vim/,/User
s/nikivi/.config/nvim/plugged/vim-go/,/Users/nikivi/.config/nvim/plugged/deoplete.nvim/,/Users/nikivi/.config/nvim/plugged/deoplet
e-go/,/Users/nikivi/.config/nvim/plugged/deoplete-ternjs/,/etc/xdg/nvim,/Users/nikivi/.local/share/nvim/site,/usr/local/share/nvim
/site,/usr/share/nvim/site,/usr/local/Cellar/neovim/0.1.4/share/nvim/runtime,/usr/share/nvim/site/after,/usr/local/share/nvim/site
/after,/Users/nikivi/.local/share/nvim/site/after,/etc/xdg/nvim/after,/Users/nikivi/.config/nvim/after', 'changedtick': 4, 'filety
pe': 'go', 'vars': {'deoplete#member#prefix_patterns': {}, 'deoplete#omni_patterns': {}, 'deoplete#omni#_functions': {'_': ''}, 'd
eoplete#sources': {}, 'deoplete#auto_complete_start_length': 2, 'deoplete#sources#go#json_directory': '', 'deoplete#max_menu_width
': 40, 'deoplete#_channel_id': 1, 'deoplete#enable_refresh_always': 0, 'deoplete#max_abbr_width': 80, 'deoplete#_rank': {}, 'deopl
ete#max_list': 100, 'deoplete#_keyword_patterns': {'_': '[a-zA-Z_]\\k*'}, 'deoplete#disable_auto_complete': 0, 'deoplete#tag#cache
_limit_size': 500000, 'deoplete#sources#go#package_dot': 0, 'deoplete#_neovim_python_version': '0.1.9', 'deoplete#_context': {}, '
deoplete#sources#go#sort_class': [], 'deoplete#sources#go#cgo': 0, 'deoplete#enable_smart_case': 1, 'deoplete#omni#input_patterns'
: {}, 'deoplete#enable_camel_case': 0, 'deoplete#sources#go#align_class': 0, 'deoplete#sources#go#gocode_binary': '', 'deoplete#fi
le#enable_buffer_path': 0, 'deoplete#enable_profile': 0, 'deoplete#omni#functions': {}, 'deoplete#_ignore_sources': {}, 'deoplete#
sources#go#use_cache': 0, 'deoplete#keyword_patterns': {}, 'deoplete#member#_prefix_patterns': {'perl': ['->'], 'ruby': ['\\.', ':
:'], 'objcpp': ['\\.', '->', '::'], '_': '\\.', 'objc': ['\\.', '->'], 'cpp': ['\\.', '->', '::'], 'php': ['->'], 'lua': ['\\.', '
:'], 'c': ['\\.', '->']}, 'deoplete#enable_ignore_case': 1, 'deoplete#sources#go#on_event': 0, 'deoplete#sources#go#pointer': 0, '
deoplete#ignore_sources': {}, 'deoplete#_omni_patterns': {'xhtml': ['<', '<[^>]*\\s[[:alnum:]-]*'], 'mkd': ['<', '<[^>]*\\s[[:alnu
m:]-]*'], 'markdown': ['<', '<[^>]*\\s[[:alnum:]-]*'], 'html': ['<', '<[^>]*\\s[[:alnum:]-]*'], 'xml': ['<', '<[^>]*\\s[[:alnum:]-
]*']}, 'deoplete#auto_complete_delay': 0, 'deoplete#omni#_input_patterns': {'ruby': ['[^. \\t0-9]\\.\\w*', '[a-zA-Z_]\\w*::\\w*'],
 'less': ['\\w+', '\\w+[):;]?\\s+\\w*', '[@!]'], 'scss': ['\\w+', '\\w+[):;]?\\s+\\w*', '[@!]'], 'lua': ['\\w+[.:]', 'require\\s*\
\(?["\']\\w*'], 'sass': ['\\w+', '\\w+[):;]?\\s+\\w*', '[@!]'], 'css': ['\\w+', '\\w+[):;]?\\s+\\w*', '[@!]']}, 'deoplete#delimite
rs': ['/', '.', '::', ':', '#'], 'deoplete#enable_at_startup': 1}, 'complete_str': ''}]'
Traceback (most recent call last):
  File "/Users/nikivi/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/__init__.py", line 57, in on_event
    self.__deoplete.on_event(context)
  File "/Users/nikivi/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 380, in on_event
-- More -- SPACE/d/j: screen/page/line down, b/u/k: up, q: quit
```

It doesn't allow me to type `:redir`

**Comment by nhooyr** [comment]
It doesn't allow you to type `:redir`? See http://vim.wikia.com/wiki/Capture_ex_command_output

**Comment by tweekmonster** [comment]
The relevant part of the error is at the bottom of the message.  You need to scroll down.  Or type this right before reproducing the error:

``` vim
:redir! > /tmp/deoplete_errors.txt
```

The text should be dumped in that file.

**Comment by zchee** [comment]
@nhooyr @Shougo @tweekmonster Thanks follow up.
@nikitavoloboev yeah, we want to more error log.

I will check your vimrc.
Also will post to how to output debug log (for remote plugin developer), please try it if you have time.

**Comment by Shougo** [comment]
@nikitavoloboev Your deoplete is the latest version?
Your deoplete does not seem support on_init feature.

**Comment by nikivdev** [comment]
@Shougo I am on 0.1.4 version. I am not sure how to upgrade it since I have downloaded it not with home-brew but with pip and `pip install nvim --upgrade` didn't seem to work.

**Comment by nhooyr** [comment]
@nikitavoloboev he said deoplete, not the neovim python client. What plugin manager do you use for neovim? Follow its instructions to update your plugins.

**Comment by nikivdev** [comment]
I use [Plug](https://github.com/junegunn/vim-plug) so I did `:PlugUpdate`. This should in theory get me the latest version. 

I have checked it again and it seems to be working. Thank you.

**Comment by torkelo** [comment]
how was this fixed?

**Comment by nhooyr** [comment]
@torkelo he updated deoplete with `:PlugUpdate`.

**Comment by torkelo** [comment]
ok, thought I tried that, but must have failed the first time :)
