### ISSUE TITLE
Error with current build

### ISSUE THREAD

**Issue by dmlyons** [zchee/deoplete-go#82]
With the current build, the first time it invokes completion this happens:

```
"~/.vim/bundle/vim-go/templates/hello_world.go" 7L, 67C
[deoplete] gocode binary not found
[deoplete] gocode binary not found
[deoplete] gocode binary not found
[deoplete] Traceback (most recent call last):
[deoplete]   File "/Users/dlyons/.vim/bundle/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 98, in gather_results
[deoplete]     ctx['candidates'] = source.gather_candidates(ctx)
[deoplete]   File "/Users/dlyons/.vim/bundle/deoplete-go/rplugin/python3/deoplete/sources/deoplete_go.py", line 139, in gather_candidates
[deoplete]     result = self.get_complete_result(self.buffer, context)
[deoplete]   File "/Users/dlyons/.vim/bundle/deoplete-go/rplugin/python3/deoplete/sources/deoplete_go.py", line 286, in get_complete_result
[deoplete]     env=env
[deoplete]   File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 947, in __init__
[deoplete]     restore_signals, start_new_session)
[deoplete]   File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 1474, in _execute_child
[deoplete]     executable = os.fsencode(executable)
[deoplete]   File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/os.py", line 862, in fsencode
[deoplete]     raise TypeError("expect bytes or str, not %s" % type(filename).__name__)
[deoplete] TypeError: expect bytes or str, not NoneType
[deoplete] Could not get completions from: go.  Use :messages for error details.
```

If I back deoplete-go out to 93bf6dca3a44889cb5ce38ff46ac6409e6e1a7dd, it works fine.

I am running on neovim, my vimrc is here: https://github.com/dmlyons/vimsetup

**Comment by zchee** [comment]
@dmlyons Maybe fixed on https://github.com/zchee/deoplete-go/commit/ec66cb1a924d4cec69315f5f3c61a703d69f5e45 by @brandonblock.
Could you re-try latest commit?

**Comment by dmlyons** [comment]
Yes, that appears to have fixed it. Thanks!

**Comment by zchee** [comment]
@dmlyons Ah, BTW small tips.
I recommended set `g:deoplete#sources#go#gocode_binary` own if you can.
because

> If you set it, deoplete-go spared look for the binary. It will improve performance.

https://github.com/zchee/deoplete-go#gocode-binary

:)
